[package]
name = "pr3"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.43.0", features = ["full"]}
regex = "1.11.1"

[[bin]]
name = "server"
path = "src/server/server.rs"

[[bin]]
name = "client"
path = "src/client/client.rs"
